export { default as HomePage } from './pages/HomePage'
export { default as ProductsPage } from './pages/ProductsPage'
export { default as SignUpPage } from './pages/SignUpPage'
export { default as PricingPage } from './pages/PricingPage'
export { default as VoiceAIPage } from './pages/VoiceAIPage'
export { default as ResourceCenterPage } from './pages/ResourceCenterPage'
export { default as ContactPage } from './pages/ContactPage'

export { default as BasePage } from './base/BasePage'
export { default as BaseComponent } from './base/BaseComponent'
